// src/game/levels.ts
import type { Level, LevelObjective, ElementSymbol } from './types';

export type { Level, LevelObjective };

// Resolve a level id against the built-in campaign, the player's published
// custom scenarios, and (for id 9999) the live editor draft metadata. Every
// objective/overlay lookup must go through this — LEVELS.find alone silently
// drops custom scenarios, making them unwinnable.
export function findLevel(
  levelId: number | null,
  customScenarios: Level[],
  editorMetadata?: {
    title: string;
    description: string;
    author: string;
    starMass: number;
    maxTurns: number;
    parMoves: number;
    objectives: LevelObjective[];
    disableSpawns: boolean;
  }
): Level | undefined {
  if (levelId === null) return undefined;
  const found = LEVELS.find(l => l.id === levelId) || customScenarios.find(l => l.id === levelId);
  if (found) return found;
  if (levelId === 9999 && editorMetadata) {
    return {
      id: 9999,
      title: editorMetadata.title,
      description: editorMetadata.description,
      author: editorMetadata.author,
      starMass: editorMetadata.starMass,
      maxTurns: editorMetadata.maxTurns,
      parMoves: editorMetadata.parMoves,
      initialTiles: [],
      objectives: editorMetadata.objectives,
      campaign: 'custom',
      disableSpawns: editorMetadata.disableSpawns,
    };
  }
  return undefined;
}

export function formatScenarioNumber(levelId: number): string {
  if (levelId >= 1000) {
    return 'Custom';
  }
  if (levelId <= 10) {
    return `1-${levelId}`;
  } else {
    return `2-${levelId - 10}`;
  }
}

// Every layout was found by searching random boards with the solver
// (src/game/solver.ts) for a single idea, a short solution, and as few working
// first moves as possible. Par is the true minimum; `npm run verify:levels`
// re-checks it. Iron tiles on a board are inert ash that act as walls.
export const LEVELS: Level[] = [
  {
    id: 1,
    title: "First Light",
    author: "Hydrogen burning",
    description: "Slide one hydrogen into the other to fuse your first helium.",
    starMass: 1.0,
    maxTurns: 3,
    parMoves: 1,
    campaign: 'nursery',
    disableSpawns: true,
    initialTiles: [{ faceId: 12, element: 'H' }, { faceId: 13, element: 'H' }],
    objectives: [{ type: "has_element", element: "He", count: 1, hint: "Drag a tile toward its neighbor and let go." }],
  },
  {
    id: 2,
    title: "Pentagon Catalyst",
    author: "The CNO shortcut",
    description: "A lone hydrogen that comes to rest on a pentagon becomes helium on its own.",
    starMass: 2.0,
    maxTurns: 3,
    parMoves: 1,
    campaign: 'nursery',
    disableSpawns: true,
    initialTiles: [{ faceId: 17, element: 'H' }, { faceId: 23, element: 'Fe' }, { faceId: 2, element: 'Fe' }],
    objectives: [{ type: "has_element_on_pentagon", element: "He", hint: "Hydrogen slides up to four faces. Find the direction that ends on a pentagon." }],
  },
  {
    id: 3,
    title: "Plan the Landing",
    author: "Slides run their full range",
    description: "Hydrogen keeps sliding until its range runs out or something stops it. Line up a slide that ends on a pentagon.",
    starMass: 3.0,
    maxTurns: 4,
    parMoves: 2,
    campaign: 'nursery',
    disableSpawns: true,
    initialTiles: [{ faceId: 14, element: 'H' }, { faceId: 22, element: 'C' }, { faceId: 8, element: 'Fe' }, { faceId: 30, element: 'Fe' }, { faceId: 2, element: 'Fe' }, { faceId: 0, element: 'Fe' }, { faceId: 3, element: 'Fe' }],
    objectives: [{ type: "has_element_on_pentagon", element: "He", hint: "The first move sets up the second." }],
  },
  {
    id: 4,
    title: "Triple-Alpha",
    author: "Helium burning",
    description: "Three helium touching in a triangle fuse into carbon.",
    starMass: 5.0,
    maxTurns: 4,
    parMoves: 2,
    campaign: 'nursery',
    disableSpawns: true,
    initialTiles: [{ faceId: 29, element: 'He' }, { faceId: 18, element: 'He' }, { faceId: 20, element: 'He' }],
    objectives: [{ type: "has_element", element: "C", count: 1, hint: "Slide a helium into another while a third touches both." }],
  },
  {
    id: 5,
    title: "Alpha Capture",
    author: "Carbon meets helium",
    description: "Carbon captures helium and becomes oxygen. Heavier nuclei only travel in straight lines.",
    starMass: 6.0,
    maxTurns: 4,
    parMoves: 2,
    campaign: 'nursery',
    disableSpawns: true,
    initialTiles: [{ faceId: 21, element: 'C' }, { faceId: 18, element: 'He' }, { faceId: 27, element: 'Fe' }, { faceId: 30, element: 'Fe' }],
    objectives: [{ type: "has_element", element: "O", count: 1, hint: "A heavy tile stops where its straight path would bend." }],
  },
  {
    id: 6,
    title: "Past Oxygen",
    author: "Neon burning",
    description: "Stars above eight solar masses keep burning: oxygen plus helium makes neon, and neon plus helium makes magnesium.",
    starMass: 12.0,
    maxTurns: 5,
    parMoves: 3,
    campaign: 'nursery',
    disableSpawns: true,
    initialTiles: [{ faceId: 28, element: 'O' }, { faceId: 15, element: 'He' }, { faceId: 21, element: 'He' }, { faceId: 20, element: 'Fe' }, { faceId: 2, element: 'Fe' }],
    objectives: [{ type: "has_element", element: "Mg", count: 1, hint: "After the first fusion, move the neon to meet the second helium." }],
  },
  {
    id: 7,
    title: "Heavy and Slow",
    author: "Magnesium barely moves",
    description: "Magnesium slides a single face, so the helium has to come to it.",
    starMass: 15.0,
    maxTurns: 4,
    parMoves: 2,
    campaign: 'nursery',
    disableSpawns: true,
    initialTiles: [{ faceId: 19, element: 'Mg' }, { faceId: 20, element: 'He' }, { faceId: 16, element: 'Fe' }, { faceId: 27, element: 'Fe' }],
    objectives: [{ type: "has_element", element: "Si", count: 1, hint: "Helium stops where its straight line would bend." }],
  },
  {
    id: 8,
    title: "Two Shells",
    author: "Silicon, twice",
    description: "Hold two silicon at once: each magnesium needs a helium of its own.",
    starMass: 18.0,
    maxTurns: 5,
    parMoves: 3,
    campaign: 'nursery',
    disableSpawns: true,
    initialTiles: [{ faceId: 20, element: 'Mg' }, { faceId: 30, element: 'Mg' }, { faceId: 21, element: 'He' }, { faceId: 31, element: 'He' }],
    objectives: [{ type: "has_element_count", element: "Si", count: 2, hint: "One helium is already close. The other needs something to stop against." }],
  },
  {
    id: 9,
    title: "Silicon Burning",
    author: "Si + Si",
    description: "Two silicon fuse into iron, the end of fusion. Silicon moves one face at a time.",
    starMass: 25.0,
    maxTurns: 5,
    parMoves: 3,
    campaign: 'nursery',
    disableSpawns: true,
    initialTiles: [{ faceId: 20, element: 'Si' }, { faceId: 31, element: 'Si' }, { faceId: 21, element: 'H' }],
    objectives: [{ type: "has_element", element: "Fe", count: 1, hint: "Walk them toward each other." }],
  },
  {
    id: 10,
    title: "Cosmic Equilibrium",
    author: "Grand finale",
    description: "Hold every element from hydrogen to iron at once. Forge the iron last, and disturb nothing else.",
    starMass: 20.0,
    maxTurns: 6,
    parMoves: 3,
    campaign: 'nursery',
    disableSpawns: true,
    initialTiles: [{ faceId: 17, element: 'H' }, { faceId: 16, element: 'He' }, { faceId: 28, element: 'C' }, { faceId: 23, element: 'O' }, { faceId: 25, element: 'Ne' }, { faceId: 22, element: 'Mg' }, { faceId: 14, element: 'Si' }, { faceId: 19, element: 'Si' }, { faceId: 20, element: 'Si' }],
    objectives: [{ type: "has_all_elements", hint: "Any stray fusion breaks the balance." }],
  },
  {
    id: 11,
    title: "Oxygen Gate",
    author: "Where products form",
    description: "A fusion product forms where its target sat. Make oxygen on a pentagon.",
    starMass: 7.5,
    maxTurns: 5,
    parMoves: 3,
    campaign: 'advanced',
    disableSpawns: true,
    initialTiles: [{ faceId: 27, element: 'C' }, { faceId: 26, element: 'He' }, { faceId: 17, element: 'Fe' }, { faceId: 2, element: 'Fe' }, { faceId: 8, element: 'Fe' }],
    objectives: [{ type: "has_element_on_pentagon", element: "O", hint: "Park the helium first, then bring the carbon." }],
  },
  {
    id: 12,
    title: "Inert Oxygen",
    author: "A light star",
    description: "In a star this light, oxygen cannot burn. It only gets in the way.",
    starMass: 7.0,
    maxTurns: 5,
    parMoves: 3,
    campaign: 'advanced',
    disableSpawns: true,
    initialTiles: [{ faceId: 27, element: 'He' }, { faceId: 21, element: 'He' }, { faceId: 26, element: 'He' }, { faceId: 29, element: 'O' }, { faceId: 11, element: 'Fe' }, { faceId: 3, element: 'Fe' }],
    objectives: [{ type: "has_element", element: "C", count: 1, hint: "Build the helium triangle around it." }],
  },
  {
    id: 13,
    title: "CNO Pinball",
    author: "Catalyst loop",
    description: "Turn a hydrogen into helium on a pentagon, then feed it to the carbon.",
    starMass: 8.0,
    maxTurns: 5,
    parMoves: 3,
    campaign: 'advanced',
    disableSpawns: true,
    initialTiles: [{ faceId: 31, element: 'H' }, { faceId: 30, element: 'H' }, { faceId: 21, element: 'C' }, { faceId: 11, element: 'Fe' }, { faceId: 8, element: 'Fe' }, { faceId: 0, element: 'Fe' }, { faceId: 3, element: 'Fe' }, { faceId: 17, element: 'Fe' }, { faceId: 27, element: 'Fe' }, { faceId: 2, element: 'Fe' }],
    objectives: [{ type: "has_element", element: "O", count: 1, hint: "The carbon has to move too." }],
  },
  {
    id: 14,
    title: "Pentagon Forge",
    author: "Neon on a pentagon",
    description: "Make neon, then bring it to rest on a pentagon.",
    starMass: 10.5,
    maxTurns: 5,
    parMoves: 3,
    campaign: 'advanced',
    disableSpawns: true,
    initialTiles: [{ faceId: 24, element: 'O' }, { faceId: 14, element: 'He' }, { faceId: 5, element: 'Fe' }, { faceId: 22, element: 'Fe' }],
    objectives: [{ type: "has_element_on_pentagon", element: "Ne", hint: "Neon slides two faces. Plan where it will stop." }],
  },
  {
    id: 15,
    title: "Only One Helium",
    author: "Keep it away from the carbon",
    description: "Fuse neon into magnesium. Your single helium must not touch the carbon or the oxygen.",
    starMass: 14.0,
    maxTurns: 5,
    parMoves: 3,
    campaign: 'advanced',
    disableSpawns: true,
    initialTiles: [{ faceId: 22, element: 'Ne' }, { faceId: 27, element: 'He' }, { faceId: 25, element: 'C' }, { faceId: 30, element: 'O' }, { faceId: 5, element: 'Fe' }, { faceId: 23, element: 'Fe' }, { faceId: 0, element: 'Fe' }, { faceId: 4, element: 'Fe' }, { faceId: 2, element: 'Fe' }, { faceId: 24, element: 'Fe' }],
    objectives: [{ type: "has_element", element: "Mg", count: 1, hint: "Move the neon, not the helium." }],
  },
  {
    id: 16,
    title: "Catalytic Cascade",
    author: "Three hydrogen, one carbon",
    description: "Make carbon from three hydrogen: each needs a pentagon, and the three helium need a triangle.",
    starMass: 9.5,
    maxTurns: 8,
    parMoves: 5,
    campaign: 'advanced',
    disableSpawns: true,
    initialTiles: [{ faceId: 28, element: 'H' }, { faceId: 20, element: 'H' }, { faceId: 22, element: 'H' }, { faceId: 9, element: 'Fe' }],
    objectives: [{ type: "has_element", element: "C", count: 1, hint: "Where each hydrogen lands decides where the triangle can form." }],
  },
  {
    id: 17,
    title: "Iron Maze",
    author: "Old ash",
    description: "Iron from an earlier star walls in the carbon. Find it a route to the helium.",
    starMass: 8.5,
    maxTurns: 5,
    parMoves: 3,
    campaign: 'advanced',
    disableSpawns: true,
    initialTiles: [{ faceId: 16, element: 'C' }, { faceId: 27, element: 'He' }, { faceId: 29, element: 'Fe' }, { faceId: 7, element: 'Fe' }, { faceId: 4, element: 'Fe' }, { faceId: 18, element: 'Fe' }, { faceId: 10, element: 'Fe' }, { faceId: 9, element: 'Fe' }, { faceId: 2, element: 'Fe' }, { faceId: 1, element: 'Fe' }, { faceId: 5, element: 'Fe' }],
    objectives: [{ type: "has_element", element: "O", count: 1, hint: "Carbon stops against iron. Use the walls as rails." }],
  },
  {
    id: 18,
    title: "Bottleneck",
    author: "One way in",
    description: "The magnesium can barely move, so the helium has to find the one way in.",
    starMass: 15.5,
    maxTurns: 5,
    parMoves: 3,
    campaign: 'advanced',
    disableSpawns: true,
    initialTiles: [{ faceId: 28, element: 'Mg' }, { faceId: 26, element: 'He' }, { faceId: 2, element: 'Fe' }, { faceId: 18, element: 'Fe' }, { faceId: 30, element: 'Fe' }, { faceId: 20, element: 'Fe' }, { faceId: 15, element: 'Fe' }, { faceId: 9, element: 'Fe' }],
    objectives: [{ type: "has_element", element: "Si", count: 1, hint: "Watch where each helium slide stops." }],
  },
  {
    id: 19,
    title: "Iron Forge",
    author: "Second silicon",
    description: "Make a second silicon beside the first, then forge iron.",
    starMass: 28.0,
    maxTurns: 5,
    parMoves: 3,
    campaign: 'advanced',
    disableSpawns: true,
    initialTiles: [{ faceId: 21, element: 'Si' }, { faceId: 27, element: 'Mg' }, { faceId: 12, element: 'He' }],
    objectives: [{ type: "has_element", element: "Fe", count: 1, hint: "A new silicon forms where the magnesium sat." }],
  },
  {
    id: 20,
    title: "Stellar Gate",
    author: "Silicon on a pentagon",
    description: "Put silicon on a pentagon, and keep your helium away from the carbon.",
    starMass: 18.0,
    maxTurns: 5,
    parMoves: 3,
    campaign: 'advanced',
    disableSpawns: true,
    initialTiles: [{ faceId: 12, element: 'Mg' }, { faceId: 17, element: 'He' }, { faceId: 16, element: 'C' }, { faceId: 1, element: 'Fe' }, { faceId: 26, element: 'Fe' }, { faceId: 18, element: 'Fe' }],
    objectives: [{ type: "has_element_on_pentagon", element: "Si", hint: "Walk the magnesium onto the gate first." }],
  },
  {
    id: 21,
    title: "Equilibrium Gates",
    author: "Under the rain",
    description: "Hold carbon, oxygen and neon at once while hydrogen rains down.",
    starMass: 12.0,
    maxTurns: 8,
    parMoves: 3,
    campaign: 'advanced',
    disableSpawns: false,
    initialTiles: [{ faceId: 12, element: 'C' }, { faceId: 16, element: 'C' }, { faceId: 15, element: 'C' }, { faceId: 31, element: 'He' }, { faceId: 17, element: 'He' }, { faceId: 27, element: 'He' }],
    objectives: [{ type: "has_element", element: "C", count: 1, hint: "Each helium has one job, and one carbon must survive." }, { type: "has_element", element: "O", count: 1 }, { type: "has_element", element: "Ne", count: 1 }],
  },
  {
    id: 22,
    title: "Double Triple-Alpha",
    author: "Two triangles",
    description: "Make two carbon from six helium. Which triangle you fuse first decides how far the second is.",
    starMass: 9.8,
    maxTurns: 5,
    parMoves: 3,
    campaign: 'advanced',
    disableSpawns: true,
    initialTiles: [{ faceId: 22, element: 'He' }, { faceId: 13, element: 'He' }, { faceId: 25, element: 'He' }, { faceId: 15, element: 'He' }, { faceId: 18, element: 'He' }, { faceId: 19, element: 'He' }, { faceId: 5, element: 'Fe' }, { faceId: 9, element: 'Fe' }, { faceId: 4, element: 'Fe' }],
    objectives: [{ type: "has_element_count", element: "C", count: 2, hint: "Fuse a triangle that leaves the other three helium close together." }],
  },
  {
    id: 23,
    title: "Silicon Chain",
    author: "Oxygen to silicon",
    description: "Climb from oxygen to silicon with three helium, in the right order.",
    starMass: 17.0,
    maxTurns: 6,
    parMoves: 4,
    campaign: 'advanced',
    disableSpawns: true,
    initialTiles: [{ faceId: 12, element: 'O' }, { faceId: 24, element: 'He' }, { faceId: 17, element: 'He' }, { faceId: 19, element: 'He' }, { faceId: 1, element: 'Fe' }],
    objectives: [{ type: "has_element", element: "Si", count: 1, hint: "Let the growing nucleus come to the helium." }],
  },
  {
    id: 24,
    title: "Cosmic Crucible",
    author: "A decoy",
    description: "Forge iron from one silicon and a magnesium. Not every nucleus here is useful.",
    starMass: 25.0,
    maxTurns: 6,
    parMoves: 4,
    campaign: 'advanced',
    disableSpawns: true,
    initialTiles: [{ faceId: 20, element: 'Si' }, { faceId: 17, element: 'Mg' }, { faceId: 14, element: 'He' }, { faceId: 12, element: 'H' }],
    objectives: [{ type: "has_element", element: "Fe", count: 1, hint: "The helium you need is not on the board yet." }],
  },
  {
    id: 25,
    title: "Supernova Ignition",
    author: "End of fusion",
    description: "Carry oxygen all the way up the ladder to silicon, then forge iron.",
    starMass: 30.0,
    maxTurns: 8,
    parMoves: 5,
    campaign: 'advanced',
    disableSpawns: true,
    initialTiles: [{ faceId: 30, element: 'Si' }, { faceId: 22, element: 'O' }, { faceId: 21, element: 'He' }, { faceId: 18, element: 'He' }, { faceId: 25, element: 'He' }],
    objectives: [{ type: "has_element", element: "Fe", count: 1, hint: "Every helium is spoken for." }],
  },
];
